### ISSUE TITLE
Add Dockerfile for 5.6

### ISSUE THREAD

**Issue by asafm** [zanox/docker-mysql#1]
I tried my self - fighting with it for 2 hours now and still fails on `Version '5.6' for 'mysql-server' was not found`

**Comment by asafm** [comment]
After figuring out I can't find mysql-server-core

**Comment by YarekTyshchenko** [comment]
Seems like MySQL switched their versions to be installed via metapackages, configurable by this utility: https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/

I'm not a fan of this. My advice is to slowly revert back to the official centos image, re-integrating the steps [here](https://github.com/mysql/mysql-docker/blob/mysql-server/5.6/docker-entrypoint.sh) into our Dockerfile, so they happen on build, so the container start is kept instant. I won't have time until next week, feel free to submit a PR.

Out of curiosity what use have you found for this image?

**Comment by asafm** [comment]
I'll give it a go. I have a few hours this week.
I'm using the official mysql image which takes 30sec to boot. Yours take
5sec without anything , just as is which is incredible.
I still haven't figured out what makes it that fast when I compare it to
the Dockerfile of official mysql.
